repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.25.0
    hooks:
      - id: eslint
        stages: [commit]

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.23.0
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
        stages: [commit]
