repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: pretty-format-json
        args: ['--autofix']
        exclude: ^(.devcontainer/|package.json|plugins/provider-dashboard/package.json)
        stages: [commit]
      - id: sort-simple-yaml
        exclude: ^(.github/ISSUE_TEMPLATE/contribute-a-plugin.yml|.github/actions/|.github/workflows|.localdevcontainer|docker-compose.yml)
        files: ^(?!\.pre-commit-config).*\.y(a)?ml
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.23.0
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
        stages: [commit]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
        exclude: ^(scripts/tests/libs/|docker|.devcontainer)
        args: ['--severity=warning']
        stages: [commit]
